### ISSUE TITLE
ALPACA 

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#106]
Couple usability suggestion for the next version of alpaca

1. Color the target mesh lighter to make the points more visible (I think this is done, I report it for the posterity). 
2. Implement a new tab to calculate a Slicer affine transform (so that ALPACA can be used as general purpose alignment tool).
3. For both single and batch processing, give an option to write the setting and re-read them. This will facilitate consistent multiple runs easier.

**Comment by smrolfe** [comment]
> Color the target mesh lighter to make the points more visible (I think this is done, I report it for the posterity).

The target mesh and the predicted landmarks now use the default color scheme (currently I believe this is yellow mesh\purple points). If the default settings are updated later they should still be a reasonable combination. The target mesh and predicted landmarks are now displayed alone at the end of the "Run CPD non-rigid registration" step.

**Comment by agporto** [comment]
I suggest the general purpose alignment tool to be a separate entity. ALPACA's code is already failry long for debugging effectively and it will be unwieldy trying to fit all those piece into a single file.

**Comment by muratmaga** [comment]
> 
> 
> I suggest the general purpose alignment tool to be a separate entity. ALPACA's code is already failry long for debugging effectively and it will be unwieldy trying to fit all those piece into a single file.

I think that's a good suggestion.

**Comment by smrolfe** [comment]
Agreed! Any name suggestions? Automated Pointcloud Registration? Automated Rigid Registration?

**Comment by agporto** [comment]
Automated Pointcloud Registration (or Automated Mesh Registration) sounds on point. If we are planning on incorporating an affine step, 'Automated Rigid Registration' wouldn't make much sense.

**Comment by muratmaga** [comment]
Adding this discussion from forum https://discourse.slicer.org/t/two-stl-file-alignment-and-measurement/8259/14
which shows the usefulness of registration aspect of alpaca for others. 

We in addition to working with models loaded into the scene (no reading from disk), we should also output a transform

**Comment by agporto** [comment]
development branch now prints the parameters used. See commit 1217d5e5f16a54f348924de33d4e19cce598badb

**Comment by SlicerMorph** [comment]
closing, tracked by #186
