### ISSUE TITLE
SlicerMOrph preferences

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#108]
I already made the changes about removing the control stroke for points, toggle persistence and lock (they are now just p, t, and l).

But for some reason cycleEffect doesn't work I am getting this error:
NameError: name 'cycleEffect' is not defined
Traceback (most recent call last):
  File "<string>", line 91, in <lambda>
NameError: name 'cycleEffect' is not defined

**Comment by SlicerMorph** [comment]
@pieper 
p, t, and l works fine in any other module I have tried (data, volume, volume rendering), but when the user switches to Markups module they stop functioning (without an error). Functionality resumes when you switch to another module.

**Comment by pieper** [comment]
This is what I mentioned before that there can be clashes between modules in terms of keys.  The Segment Editor also defines shortcuts per-effect that might clash.

We should probably make an inventory of which keys are used in which modules.  Easiest would be to just pick other keys, but if that's not possible we could look into adding configurations to the main app to say which shortcuts should have priority.

**Comment by SlicerMorph** [comment]
I am not sure how to go about documenting other modules shortcuts. There is nothing noted in the Markups module for key shortcuts: https://slicer.readthedocs.io/en/latest/user_guide/modules/markups.html

Pressing the p doesn't seem to do anything in Markups module (after disabline SlicerMOrph preferences)

**Comment by pieper** [comment]
It's in [defined in the code](https://github.com/Slicer/Slicer/blob/2b3e7af4dc6a4733f1f55ad139bd68daa1ed34ac/Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx#L793-L803) but yes, the implementation could be broken.

There are not many places where shortcuts are defined but extensions, like ours, might define their own.
https://github.com/Slicer/Slicer/search?q=QShortcut

Just picking a different key for now is the most workable.  Ultimately we'll need some kind of user preference interface so people can choose which ones should be active, but this will take some thought.

**Comment by SlicerMorph** [comment]
For this particular case using p for placing fiducials, isn't that's what their implementation is supposed to be doing? They really should fix it, as oppose to we try to re-invent the wheel, or remove it. I am open to changing the others but for fiducials using P makes sense for Placing Points. (hence that's why they are using too I suppose).

**Comment by muratmaga** [comment]
Also let's set the SlicerMorph prefs to unchecked (due to Andras' objection to interpolation etc).
