### ISSUE TITLE
ImportFromURL works only for volume data currently

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#120]
Please revise to work with any data type Slicer accepts (3D models, fiducials, transforms, etc) not just models, including zip files. If it is a zip, action should be just unzipping to the temp folder, do not load into the scene. 

There is now a preference in the SlicerMorph preferences to set the temp location for both cache and Temp folder the same location.

**Comment by smrolfe** [comment]
Fixed in commit 3361ccc2469991141c6431ae5da47f54f1971854
