### ISSUE TITLE
importing open3d<0.10 crashes Slicer in Linux in latest stable and preview versions

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#123]
This is a due to an incompatibility with glibc libraries. 

It renders ALPACA unusable in most Linux systems including Centos8 or Ubuntu 20.04. We will either have to update the ALPACA to use open3d >=0.10 on all platforms, or disable ALPACA for Linux. 

I propose to open a separate development branch for migration to open3d 0.10.0

**Comment by agporto** [comment]
#124 should fix the issue.
