### ISSUE TITLE
.NII is not recognized as a valid format in ImportFromURL

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#125]
Testing with this data:
http://www.bic.mni.mcgill.ca/uploads/ServicesAtlases/macaque_25_model-MNI.nii

Error is:

Switch to module:  "ImportFromURL"
Could not download data. Not a supported file type.
Could not import data. Please confirm that the URL and file name is valid.

**Comment by smrolfe** [comment]
Fixed missing file type here: https://github.com/SlicerMorph/SlicerMorph/commit/7da187bad5e1b32164dca44b773bf11dddb85d06
