### ISSUE TITLE
Add new features to SkyscanReconImport

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#128]
Requested by Adam Summers
* Add displaying the amount of memory required to load the volume as parsed from the log file. 
* Add downsampling options similar to ImageStacks (need to circumnavigate loading the whole volume issue first).

**Comment by muratmaga** [comment]
completed via https://github.com/SlicerMorph/SlicerMorph/commit/e3e7e65ded8cd81cd8b3a0452b3af95618c84de0
