### ISSUE TITLE
Add new tag to Markup JSON to distinguish different landmark types from SlicerMorph

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#129]
We need to be able to tell fiducials that are anatomical landmarks from constructed landmarks such as semi-landmarks generated by curve resampling or from GeneratePseudoLMs or CreateSemiLMPatches modules of SlicerMorph. Certain morphometric methodologies treat the latter  differently (e.g., sliding them to minimize bending energy) and it is important to retain this distinction. 

Can we extend the Markups JSON format to create such a tag?

@pieper @smrolfe

**Comment by pieper** [comment]
I would say yes, but will defer to @smrolfe since she's been deep in this code recently.  I don't know if there's an existing way to add extra attributes like that easily as part of the extension or if it would require some extra hooks in the Markups code.  Either way it sounds like a good thing to add.

**Comment by smrolfe** [comment]
Thanks @pieper , I am going to start a conversation on discourse on the best way to do this.

**Comment by smrolfe** [comment]
I've modified PseudoLMGenerator and CreateSemiLMPatch modules to add an array with landmark type that's stored in the JSON file. Still to do is checking for and propagating this array when landmark points are transferred. This will impact: ALPACA, PlaceSemiLMPatches, ProjectSemiLM.

**Comment by SlicerMorph** [comment]
Per our discussion let's use the Description field of the Markups table to indicate the type of the landmarks:
Fixed for anatomical landmarks
Semi: for all computationally derived ones (both pseudo and patches).

We need should modify our parsers and indicate those in the log file as well. (and possibly as a warning message in GPA. E.g., something like there are semi-LM in the datasets, GPA in SlicerMorph does not allow sliding of semiLMs).
