### ISSUE TITLE
Calculate better zoom level for mean shape point rendering

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#130]
When the gpa is executed, and the mean shape points become visible in the 3D viewer, they are very far requiring the user to zoom in quite a bit. Would it be possible to calculate a better zoom in level, so that things are visible better? See screenshot below

![image](https://user-images.githubusercontent.com/21285140/107711675-df1e9500-6c7c-11eb-9e08-845e391578a6.png)
vs 
![image](https://user-images.githubusercontent.com/21285140/107711705-eb0a5700-6c7c-11eb-9e94-e47f0543ce68.png)

Zoom level is better when the skip scaling step is enabled. Perhaps we can do the calculation of alignment and procrustes residuals in scaled data, but when rendering the points put the scale back in.

**Comment by smrolfe** [comment]
Fixed here: https://github.com/SlicerMorph/SlicerMorph/commit/48dbf36f7e25581eae82e59f31db7c211114e306

This is working for some datasets at very different scales, but testing on more new data would be helpful.
