### ISSUE TITLE
Write a log file of input parameters to output folder

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#131]
This should be a flat text file with things such as:
Input folder
fcsv file names
Number of landmarks
LMs skipped = NULL 
whether the scaling is enabled or not

We need something like this for programmatic interface in R. That way all we need to do is to point to this file and we can call everything necessary.

**Comment by muratmaga** [comment]
A sample files are included here: 
[analysis.log](https://github.com/SlicerMorph/SlicerMorph/files/6025274/analysis.log)
[json.log](https://github.com/SlicerMorph/SlicerMorph/files/6025275/json.log)

**Comment by smrolfe** [comment]
Addressed in commit: https://github.com/SlicerMorph/SlicerMorph/pull/135/commits/91b883471bcb21577f845646d603f60c90ec694c

**Comment by muratmaga** [comment]
thanks.
