### ISSUE TITLE
Can't do visualizations for previously run GPA

### ISSUE THREAD

**Issue by DiamondKMG** [SlicerMorph/SlicerMorph#140]
The GPA loads and everything shows up for the analysis, but when I switch to the 'explore data' or 'interactive visualizations' tab I'm not able to do any visualizations. I've coppied the log message below. I was reloading a gpa for the SlicerMorph mouse skull example. I was able to do everything on all tabs if I rerun the analysis from the fcsv files but not if I load from file. 

[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Session start time .......: 2021-03-01 16:05:25
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Slicer version ...........: 4.11.20210226 (revision 29738 / 7a593c8) macosx-amd64 - installed release
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Operating system .........: macOS / 11.2.1 / 20D74 / UTF-8 - 64-bit
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Memory ...................: 16384 MB physical, 2048 MB virtual
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - CPU ......................: GenuineIntel Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz, 2 cores, 4 logical processors
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, Sequential threading
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Qt configuration .........: version 5.15.1, with SSL, requested OpenGL 3.2 (core profile)
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Developer mode enabled ...: yes
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Application path .........: /Applications/Slicer 3.app/Contents/MacOS
[DEBUG][Qt] 01.03.2021 16:05:25 [] (unknown:0) - Additional module paths ..: Extensions-29738/Auto3dgm/lib/Slicer-4.11/cli-modules, Extensions-29738/Auto3dgm/lib/Slicer-4.11/qt-scripted-modules, Extensions-29738/DeveloperToolsForExtensions/lib/Slicer-4.11/qt-scripted-modules, Extensions-29738/MarkupsToModel/lib/Slicer-4.11/qt-loadable-modules, Extensions-29738/ModelToModelDistance/lib/Slicer-4.11/cli-modules, Extensions-29738/RawImageGuess/lib/Slicer-4.11/qt-scripted-modules, Extensions-29738/Sandbox/lib/Slicer-4.11/qt-loadable-modules, Extensions-29738/Sandbox/lib/Slicer-4.11/qt-scripted-modules, Extensions-29738/SlicerDcm2nii/lib/Slicer-4.11/qt-scripted-modules, Extensions-29738/SlicerIGT/lib/Slicer-4.11/qt-loadable-modules, Extensions-29738/SlicerIGT/lib/Slicer-4.11/qt-scripted-modules, Extensions-29738/SlicerJupyter/lib/Slicer-4.11/qt-loadable-modules, Extensions-29738/SlicerJupyter/lib/Slicer-4.11/qt-scripted-modules, Extensions-29738/SlicerMorph/lib/Slicer-4.11/qt-scripted-modules, Extensions-29738/SurfaceWrapSolidify/lib/Slicer-4.11/qt-scripted-modules
[DEBUG][Python] 01.03.2021 16:05:26 [Python] (/Applications/Slicer 3.app/Contents/lib/Python/lib/python3.6/site-packages/pydicom/datadict.py:432) - Reversing DICOM dictionary so can look up tag from a keyword...
[WARNING][Qt] 01.03.2021 16:05:33 [] (unknown:0) - libpng warning: iCCP: profile 'ICC Profile': 'CMYK': invalid ICC profile color space
[WARNING][Qt] 01.03.2021 16:05:33 [] (unknown:0) - libpng warning: iCCP: known incorrect sRGB profile
[DEBUG][Python] 01.03.2021 16:05:34 [Python] (/Applications/Slicer 3.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 01.03.2021 16:05:35 [Python] (/Applications/Slicer 3.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 01.03.2021 16:05:35 [Python] (/Applications/Slicer 3.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Python] 01.03.2021 16:05:35 [Python] (/Applications/Slicer 3.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: ExportAs
[INFO][Python] 01.03.2021 16:05:35 [Python] (<string>:3) - Customizing with SlicerMorphRC.py
[INFO][Python] 01.03.2021 16:05:35 [Python] (<string>:12) -   Volume nodes will be stored uncompressed by default
[INFO][Python] 01.03.2021 16:05:35 [Python] (<string>:20) -   Segmentation nodes will be stored uncompressed
[INFO][Python] 01.03.2021 16:05:35 [Python] (<string>:170) -   9 keyboard shortcuts installed
[INFO][Python] 01.03.2021 16:05:35 [Python] (<string>:172) - Done customizing with SlicerMorphRC.py
[INFO][Python] 01.03.2021 16:05:35 [Python] (<string>:173) - On first load of customization, restart Slicer to take effect.
[DEBUG][Qt] 01.03.2021 16:05:35 [] (unknown:0) - Switch to module:  "Data"
[INFO][Stream] 01.03.2021 16:05:35 [] (unknown:0) - Customizing with SlicerMorphRC.py
[INFO][Stream] 01.03.2021 16:05:35 [] (unknown:0) -   Volume nodes will be stored uncompressed by default
[INFO][Stream] 01.03.2021 16:05:35 [] (unknown:0) -   Segmentation nodes will be stored uncompressed
[INFO][Stream] 01.03.2021 16:05:35 [] (unknown:0) -   9 keyboard shortcuts installed
[INFO][Stream] 01.03.2021 16:05:35 [] (unknown:0) - Done customizing with SlicerMorphRC.py
[INFO][Stream] 01.03.2021 16:05:35 [] (unknown:0) - On first load of customization, restart Slicer to take effect.
[INFO][Python] 01.03.2021 16:05:36 [Python] (<string>:20) - Volume nodes will be stored uncompressed by default
[INFO][Python] 01.03.2021 16:05:36 [Python] (<string>:26) - Segmentation nodes will be stored uncompressed
[INFO][Stream] 01.03.2021 16:05:36 [] (unknown:0) - Loading Slicer RC file [/Users/kellydiamond/.slicerrc.py]
[INFO][Stream] 01.03.2021 16:05:36 [] (unknown:0) - Volume nodes will be stored uncompressed by default
[INFO][Stream] 01.03.2021 16:05:36 [] (unknown:0) - Segmentation nodes will be stored uncompressed
[DEBUG][Qt] 01.03.2021 16:06:34 [] (unknown:0) - Switch to module:  "GPA"
[WARNING][Qt] 01.03.2021 16:06:36 [] (unknown:0) - QGestureManager::deliverEvent: could not find the target for gesture
[INFO][Stream] 01.03.2021 16:06:56 [] (unknown:0) - mShape shape (54, 3)
[INFO][Stream] 01.03.2021 16:06:56 [] (unknown:0) - Loaded 126 subjects with 54 landmark points.
[INFO][Stream] 01.03.2021 16:06:56 [] (unknown:0) - Scale Factor: 0.457814781126457
[CRITICAL][Qt] 01.03.2021 16:06:57 [] (unknown:0) - setViewLabel should be called before setViewNode !
[CRITICAL][Qt] 01.03.2021 16:06:57 [] (unknown:0) - setViewLabel should be called before setViewNode !
[CRITICAL][Qt] 01.03.2021 16:06:57 [] (unknown:0) - setViewLabel should be called before setViewNode !
[CRITICAL][Qt] 01.03.2021 16:06:57 [] (unknown:0) - setViewLabel should be called before setViewNode !
[CRITICAL][Qt] 01.03.2021 16:06:57 [] (unknown:0) - setViewLabel should be called before setViewNode !
[CRITICAL][Qt] 01.03.2021 16:06:57 [] (unknown:0) - setViewLabel should be called before setViewNode !
[CRITICAL][Qt] 01.03.2021 16:06:57 [] (unknown:0) - setViewLabel should be called before setViewNode !
[INFO][Stream] 01.03.2021 16:06:57 [] (unknown:0) - Closest sample to mean:4028_S
[CRITICAL][Stream] 01.03.2021 16:06:57 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 01.03.2021 16:06:57 [] (unknown:0) -   File "/Applications/Slicer 3.app/Contents/Extensions-29738/SlicerMorph/lib/Slicer-4.11/qt-scripted-modules/GPA.py", line 551, in onLoadFromFile
[CRITICAL][Stream] 01.03.2021 16:06:57 [] (unknown:0) -     if(not self.skipScalingOption):
[CRITICAL][Stream] 01.03.2021 16:06:57 [] (unknown:0) - AttributeError: 'GPAWidget' object has no attribute 'skipScalingOption'

**Comment by smrolfe** [comment]
Thanks for catching this @DiamondKMG, fixed here: https://github.com/SlicerMorph/SlicerMorph/commit/2cd2e0821f3bc7b04830253faba3b9127d054d3d

I did not need change the log file format, since when I went back and checked, we'd already included this parameter.

**Comment by smrolfe** [comment]
There's still an issue with the 2D projection/zoom when loading from file with no scaling. I will follow up on this.

**Comment by smrolfe** [comment]
Last minor display bug fixed here: https://github.com/SlicerMorph/SlicerMorph/commit/2cd2e0821f3bc7b04830253faba3b9127d054d3d
