### ISSUE TITLE
Provide a popup error message for GPA data load issues

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#141]
If a sample has more or less LMs than the rest, GPA module will fail to work and throw an error. This error is now outputed to python console which may not be visible to the users. Change the GPA functionality to produce a popup error and display a meaningful message such:

**Sample(s) X/Y have more/less LMs than the rest. Make sure all your samples have identical sets of LMs**

instead of the dimensionality error numpy throws when it reads it into file array. In fact we better make this a precheck before the trying to load the files.

**Comment by smrolfe** [comment]
Added error pop-up here: a6db822ad488d0784d27a1660d85ede0b69ca75d

Also adds error pop-up to the load from file to make it more obvious when this fails.
