### ISSUE TITLE
Add a utility to stitch individual semi LM curves into a single curve

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#142]
By definition the first and last points on the curve semi-LM are treated fixed. So when users need to create a series of curves that are continuous in nature (e.g., dorsal skull profile, in which control points are different sutures zones), and merge them together, there will be duplications (the last point of the first curve, and the first point on the second curve will be identical) in the resultant file.

Create a utility to drag individual MarkupsCurve nodes into a hierarchy, order them as user wanted them, and when they hit apply, it will merge them as a single markups node. It should have an option that is checkbox which reads, curves are continuous (meaning when merging, the redundant points should be removed, and not removed if they are not contiuous)

See more discussion on forum here:

https://discourse.slicer.org/t/markups-creating-a-single-file-including-landmarks-fixed-and-curves-semilandmarks-problem-while-resampling/16158/6

**Comment by SlicerMorph** [comment]
Referencing #129 for output table (semi vs fixed).

**Comment by smrolfe** [comment]
Added module here: https://github.com/SlicerMorph/SlicerMorph/commit/39ea877e857452b457ddc8efac1e905c4cc40d5e

Leaving open until a few UI design questions are addressed.

**Comment by smrolfe** [comment]
A few notes on the this module development:

Should this only include curves or would it be useful for other markup types? (lines, fiducials)
When is it useful to keep redundant points?
How close are redundant points allowed to be?
Is there a case where the landmark order of a curve may need to be reversed?
Should the points keep their original labels?

**Comment by smrolfe** [comment]
Updates addressed here: https://github.com/SlicerMorph/SlicerMorph/commit/1f694be59816569bcb858c8af8d67cf3eb78eb4a
