### ISSUE TITLE
ExportAs does not display files in the folder that match the selected format 

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#143]
Create a random data, use exportAs to save it to a folder. 
Then use exportAs one more time, and point it to the same folder and note that previously created file is not displayed in the file dialog box (makes the folder look empty and displays "no items matched to your criteria"). Repos for the latest stable on windows.

**Comment by pieper** [comment]
I see, yes, this is different behavior from mac, where other file is shown grayed out.
