### ISSUE TITLE
Make interactive section of ALPACA work with models loaded into the scene

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#154]
It is a bit weird and unintuitive that interactive mode wants to read the input from the file. 

If we are going to implement interactive registration #106, I am fine with leaving the layout as it. But otherwise we need to make it work with models loaded into the scene

**Comment by agporto** [comment]
Solved with commit ab64a17ed380c94101851587e5426d6e9f1caa2b in the development branch. Close issue after testing
