### ISSUE TITLE
improve large volume import workflow

### ISSUE THREAD

**Issue by pieper** [SlicerMorph/SlicerMorph#16]
From Murat:

> I really would like to see an automated conversion of vector2scalar volume during the data import phase for bmp/jpg/png stacks (tiff doesn’t suffer from this). The way I envision is an extra checkbox in options for people who installed SlicerMorph, if we cannot do it default for everyone.  If we can get pass that point, things will be a lot more easy for the folks. What’s happening is they are using 3 times as much memory for volumes that are already fairly big to begin with (almost everyone worked with datasets >1GB, sometimes 5-6GBs), and almost all volumes coming from bruker/skyscan microcts are bmps (which is the default output option in their post-processing software). And there are a lot of data coming from those scanners.

**Comment by SlicerMorph** [comment]
New ImageStacks alleviates this issue
