### ISSUE TITLE
Animator yellow outline in gif output

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#160]
To reproduce:
1. Load Mrhead
2. Render with a white background. 
3. Set a rotation in Animator, choose output as gif.
4. Save the output and observe that there is a yellow outline in the saved image (doesn't exist during rendering).

Try the same rotation in Screen Capture with animated gif output, and observe that it does NOT happen. Refered in https://discourse.slicer.org/t/slicermorph-animator-yellow-highlight-on-gif-images/17653

 
![image](https://user-images.githubusercontent.com/21285140/118519380-eb881300-b6ed-11eb-92ec-326133baf1b0.png)

**Comment by pieper** [comment]
See comment on discourse.  This is probably a limitation of the gif format.

**Comment by muratmaga** [comment]
I saw it, but as I said it doesn't happen with screen capture module. So I am assuming it is a combination of encoding parameters specified in animator.

**Comment by pieper** [comment]
No, I think it's the image size.  Let's keep the discussion over on discourse and come back to this when we reach an action plan.
