### ISSUE TITLE
import landmarks from a slicer table

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#167]
Inspired by [the thread and similar ones](https://discourse.slicer.org/t/importing-landmarks-from-excel-file-into-3d-slicer/17910/6), let's explore the possibility of importing LM coordinates from a slicer table into a MarkupFiducial node. 

1. User creates a csv file that they can read into Slicer as a table. 
2. This utility function reads (or copy/pastes) the values into a fiducial node. 

@pieper @smrolfe

**Comment by pieper** [comment]
This makes sense as long as we don't run into performance issues.  I haven't characterized fully, but I did find that a csv of about 10k rows by 20 columns was terribly slow (on the order of hours to load) so we may need to look into that before relying on tables for large automated landmark extraction files.

**Comment by muratmaga** [comment]
Looks like andras best us to it.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by muratmaga** [comment]
https://discourse.slicer.org/t/importing-landmarks-from-excel-file-into-3d-slicer/17910/8

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by pieper** [comment]
Yes, I hope it works well for this.  My case was not for Tarkups but for a different csv that I thought would be convenient to use with the Table infrastructure but it's not usable with current performance.  Let's see how it works for your use cases.

**Comment by muratmaga** [comment]
resolved via new table import in markups
