### ISSUE TITLE
Continue analysis from where we left

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#17]
Need a mechanism to save the GPA module analysis, reload and continue from where it is left. While analysis is fast for demo sets, it takes a while for larger samples sizes, and customization (labels, etc) are lost.

**Comment by SlicerMorph** [comment]
@pieper saving a scene doesn't seem to recover the state of the analysis. Any suggestions on how to accomplish this?

**Comment by pieper** [comment]
In the Animator I save all the state in json as an attribute of a mrml node.  It's generally not very much data so it's lightweight to use this approach and it would probably work for GPA as well.

https://github.com/pieper/SlicerAnimator/blob/master/Animator/Animator.py#L854-L861

**Comment by smrolfe** [comment]
Since a results file is written out for each run, the module can restore its state from the contents of the folder. Added functions to recover the analysis from the output results file in commit 36fa27ce1913b4a7e032fcc6b9d19c6b61af675e.
