### ISSUE TITLE
ALPACA renames points

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#170]
The current behavior in alpaca to rewrite the landmark labels with something like:
"Refined_Predicted_Landmark_XX"
This is too long of a label to useful display. Also, since it overwrites the original labels, sometimes it is hard to find which landmark is which when there is a cluster of points. 

Please revise this behavior such that whatever the input the LM labels are preserved, but add suffices:
-fin (what we used to call refined) or -ini (initial placement) 
depending on the situation
@smrolfe @agporto

**Comment by agporto** [comment]
Does it need the suffix? I've implemented one that copies the original label  in both master and development branches. See f33a1fc5050a8246f699a2226e53609f7a4f5a49 . If you are ok with the behavior, feel free to close the issue.

**Comment by agporto** [comment]
To be clear, it is trivial to add the suffix. I am just suggesting the user might not need it.

**Comment by muratmaga** [comment]
I will give it a try as is. You might be right that suffixes might be necessary.

**Comment by SlicerMorph** [comment]
closing, now tracked by #186
