### ISSUE TITLE
ALPACA display rigid aligned meshes button bug

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#171]
In the stable branch, I accidentally clicked the "Display rigid aligned meshes" twice, for whatever reason thinking it will toggle the display of the mesh back to point cloud. 

This had the surprising effect of moving the mesh further away from the source (it was aligned in the first hit). Keep hitting the same button moved the target mesh further and further away. This tells me resultant transformation is applied every time it is clicked.

Couple options:

1. Indeed change the button behavior to toggle like I was expecting initially.
2. Gray out the button and make it inactive after the first round, so people can't accidentally do what I did.

@agporto @smrolfe

**Comment by SlicerMorph** [comment]
closing, now tracker by #186
