### ISSUE TITLE
Should integrate ImageStacks, Animator, SemiLandmarks into the Lab module

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#18]

**Comment by SlicerMorph** [comment]
Still need the ImageStacks and Animator.

**Comment by pieper** [comment]
I thought the plan was just to drop the modules into the customized version?

**Comment by SlicerMorph** [comment]
They are already present in the customized version. But we need a more manageable way of incorporating changes in external modules. Clone, copy/replace existing module, and repackage is error prone. Having them under the main package will make things a lot more straightforward, and easier for extension users as well. But I am open to suggestions.

**Comment by pieper** [comment]
While [this pull request](https://github.com/Slicer/Slicer/pull/1227) is still pending and under discussion, we will need to restart the application when switching module versions.  I don't think this is terrible, just inconvenient.
