### ISSUE TITLE
ALPACA GUI Updates

### ISSUE THREAD

**Issue by smrolfe** [SlicerMorph/SlicerMorph#186]
To-do list from meeting on 12/14

- [ ] Open3D upgrade

- [ ] Address the current file activation order inconsistencies.

- [ ] Add a run all button?

- [ ] New division of actions and results browser allowing return to previous visualizations

- [ ] Default display for final step should be estimated landmarks on target

- [ ] Add option to load gold-standard landmarks for RMSEE comparison

- [ ] Show registered source model for registration parameter adjustment

- [ ] Two opacity sliders for visualizing registered source/target

- [ ] Slider to adjust point size

- [ ] Increment output model point color and name
       Dark Bright Chart colors for landmarks
       Medium Chart colors for landmarks

- [ ] Propagate the landmark names from the template to estimated landmark nodes

- [ ] Improve landmark node names (include subject id)

- [ ] Save/load settings menu options under the advanced tab

- [ ] Split JSON output file into two sections, setting and file locations, to cover case where only settings are being saved.

**Comment by muratmaga** [comment]
updated via #210
