### ISSUE TITLE
Registration of Meshes

### ISSUE THREAD

**Issue by stevenagl12** [SlicerMorph/SlicerMorph#187]
Is there any way that you could build in the option of utilizing the principle axis and then using an assortment of points across the surface for iterative closest point registration (ICP) to decrease the distance between random candidate pseudo-landmarks in an iterative fashion. The implementation in python can be found through the menpo project at: https://www.menpo.org/menpofit/result.html, or through another project at: https://github.com/Minisal/icp-python., https://laempy.github.io/pyoints/tutorials/icp.html, or https://github.com/agnivsen/icp. This would enable a decent fit and we could use these landmarks as a pseudo statistical shape model created from the PCA that preserves the volume of the objects which might be important for pathologies. It would also be nice to be able to label the centroid points in the SlicerMorph scene created after performing procrustes alignment for which landmarks are which if working without pseudo-landmarks, and to be able to select a point and show the histogram of the data, to demonstrate whether the population of points at that location have a bimodal, gaussian, or other distribution.

**Comment by muratmaga** [comment]
We are working on other methods that allow better correspondence of dense points extracted from meshes on a separate project. When it matures enough to be used by others, we can ping you. 

Meanwhile it is unlikely at this point we will work on this without actual project that is funded for it. However, all these building blocks are available, including example of ICP in ALPACA, if you want to experiment on it via scripts.

**Comment by muratmaga** [comment]
This is now available via the FastModelAlign. See tutorial at https://github.com/SlicerMorph/Tutorials/tree/main/FastModelAlign
