### ISSUE TITLE
Latest Slicer does not start on windows after installing SlicerMorph

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#191]
Download the latest slicer (r30566). Install SlicerMorph, but don't choose to install any of the dependencies. Restart slicer, and notice that it is stuck at the splash screen at "instantiating modules" stage. This is the log file contents:

[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Session start time .......: 2022-01-28 19:34:36
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Slicer version ...........: 4.13.0-2022-01-27 (revision 30566 / 8f834f6) win-amd64 - installed release
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Operating system .........: Windows /  Professional / (Build 22000, Code Page 65001) - 64-bit
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Memory ...................: 32495 MB physical, 96495 MB virtual
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - CPU ......................: GenuineIntel , 16 cores, 16 logical processors
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Qt configuration .........: version 5.15.2, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Internationalization .....: disabled, language=
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Developer mode ...........: enabled
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Application path .........: C:/Users/murat/AppData/Local/NA-MIC/Slicer 4.13.0-2022-01-27/bin
[DEBUG][Qt] 28.01.2022 19:34:36 [] (unknown:0) - Additional module paths ..: NA-MIC/Extensions-30566/SlicerOpenAnatomy/lib/Slicer-4.13/qt-scripted-modules, NA-MIC/Extensions-30566/DeveloperToolsForExtensions/lib/Slicer-4.13/qt-scripted-modules, NA-MIC/Extensions-30566/SlicerMorph/lib/Slicer-4.13/qt-scripted-modules

@smrolfe

**Comment by pieper** [comment]
Hmm, the latest nightly works for me on linux with or without the slicer morph dependencies.

As an aside, why wouldn't you install the dependencies?  It seems like people would expect things not to work if they don't install all the dependencies.  (Granted, the app should start).

Note that that there are some python packages being installed at startup time and these could take a while and there is no progress bar.  The modules could be refactored to bring up a dialog box after the app has started saying that additional packages need to be downloaded to complete the installation and the user could be given the option of downloading them so at least they would know what's going on and not think the app is hung. (This may or may not be what Murat is reporting but it could be a good change in any case).

**Comment by smrolfe** [comment]
I also haven't been able to replicate this on Windows (with the same r30566).

**Comment by muratmaga** [comment]
@pieper, I decided to not install the extensions after the second installation attempt to rule out that dependencies are not what's causing the block.
I still cannot get it to work, but if it doesn't repllicate for you, I am not so concerned. Will try with a newer Slicer.

**Comment by muratmaga** [comment]
does not repro beyond one computer. Probably corrupted ini file or something else...
