### ISSUE TITLE
CreateSemiLMPatches - Projection issue

### ISSUE THREAD

**Issue by liver121888** [SlicerMorph/SlicerMorph#192]
I wish to create semiLMs patches using F-84048-9, F-84048-7, F_1-3 in an oral cavity model

![image](https://user-images.githubusercontent.com/68542467/151655155-c594cdb9-165b-48db-adb0-67b83093338c.png)

I initially thought that the semiLMs would be only on the surface below or above the plane these three LM form, but some semiLMs would also appear outside of the oral cavity

![image](https://user-images.githubusercontent.com/68542467/151655256-47ed3241-191a-40b5-a562-3f24cd0e5406.png)

From another POV, the patch looks well but not the way I want it (inside the oral cavity)

![image](https://user-images.githubusercontent.com/68542467/151655289-17931666-48a1-4a0d-92bf-4b02ca2b7afc.png)

Is there any method I can constraint the LMs generated to be under the plane of the 3 fixed LMs? Like a projection which starts from the plane they generated.

I am using SlicerMorph published on Thu Oct 21 2021

**Comment by muratmaga** [comment]
It will quite hard to control where the points will be in a curved region like oral cavity. and it may not be possible to have regular spacing between the points. Patches makes more sense for smoothly changing surfaces. 

Having said that you want to adjust the "max projection distance" (under advanced settings) to test if it lets you do patch closer to what you want. 
![image](https://user-images.githubusercontent.com/21285140/151722860-672b0cc7-3876-45db-b5e9-e10d80a5b0fb.png)

**Comment by liver121888** [comment]
Thanks for your answer, changing the projection distance solved my issue.
