### ISSUE TITLE
PC wrapped model orientation in GPA Module 

### ISSUE THREAD

**Issue by liver121888** [SlicerMorph/SlicerMorph#194]
I am trying to create a morphable oral cavity model, and below is the model closest to the mean and its corresponding LMs in green. The LMs in red is the mean LMs.

![image](https://user-images.githubusercontent.com/68542467/154936202-94bad4d5-c468-4a3f-a12a-36177e50f932.png)

When I try to use 3D model visualization using the same LMs and model closest to the mean, the output orientation is inverted. 

![image](https://user-images.githubusercontent.com/68542467/154938531-de67e8c6-35b4-4932-9f25-a52b6aef22d8.png)

I expected its orientation should be similar to this (the uvula should pointing to the observer) only with the edge is morphed to match the mean 

![image](https://user-images.githubusercontent.com/68542467/154940202-c6142c0f-12ba-49ec-9b94-8f2b2a21710c.png)

I think the problem is somehow related to the difference between RAS system and the LPS system. The model I am using is created by segment editor in STL format, and I am sure I export it under RAS system. I also tried vtk format, which cannot select coordinate system but the result is the same (inverted).

I am new to slicer and SlicerMorph so any help would be quite helpful, thanks.

I am using SlicerMorph published on Thu Oct 21 2021

**Comment by smrolfe** [comment]
Thanks @liver121888 are you able to share one of these models with me?

**Comment by liver121888** [comment]
@smrolfe thanks for your reply.

The last time I use nightly versions the required extension "sandbox" could not be downloaded from the extension manager so I stick with the older version.
I tried with the preview version: revision 30625 on Windows this morning, the same error occurs.

The below link is the link to the model and the LMs.
https://drive.google.com/drive/folders/1Rwxb3b6dsNzyB2fLigZffEWca_LY_TPY?usp=sharing

I checked the header in the STL files, they are in RAS format. The LMs I use were in LPS format but I later finds out the module only reads LMs in RAS format (if LMs were in LPS, the orientation would be opposite and without a warning or a message), so I turned them into RAS manually by assgining negative signs and modified the header to RAS. Thus, you can see I label every LMs in file name with "RAS". I think the module should tell the user the coordinate system being used otherwise the user may get confused.

**Comment by liver121888** [comment]
A little more digging in the code and trial-and-error led me to the conclusion that the issue is not regarding the model using LPS or RAS.
The reason is that my LMs distribution is too planar, so the module cannot distinguish the orientation.
With more LMs in the R-A direction, the problem is solved. Also, the shear affine effect is lessened, too.
But the LMs input to the GPA still has to be in RAS.
I am not sure whether I concluded it right, but it came from my observation.

## _LMs distribute in planar, the shear affine effect is strong, so the integrity of the model is lost_
The barrel shape is distorted
![image](https://user-images.githubusercontent.com/68542467/158059518-354ad0b2-4091-4b2e-92eb-268695ec1ad2.png)
corresponding mean LMs
![image](https://user-images.githubusercontent.com/68542467/158060018-901d2fb4-8d66-4299-9e01-cb0f3c6d86ff.png)


## _With more LMs in the R-A direction, the shear affine is lessened and the model shape remains intect_
The barrel shape is kept
![image](https://user-images.githubusercontent.com/68542467/158059771-3162883c-6fe3-42e3-99ec-967ec62c7074.png)
corresponding mean LMs
![image](https://user-images.githubusercontent.com/68542467/158060023-704d2e2f-b369-44d9-87be-ca79b87bb12a.png)
