### ISSUE TITLE
Add support for enabling/disabling specific modules

### ISSUE THREAD

**Issue by jcfr** [SlicerMorph/SlicerMorph#207]
## Is your feature request related to a problem? Please describe.

In the context of custom applications, we are interested in including specific functionality of `SlicerMorph` without introducing extraneous dependencies.

## Describe the solution you'd like

Introduce an option called `SlicerMorph_BUILD_DEFAULT_MODULES` enabled by default.

By default, all modules currently associated with `add_subdirectory` in the top-level `CMakeLists.txt` are built.

* When `SlicerMorph_BUILD_DEFAULT_MODULES` is set to `OFF`
  * No module is built
  * Module are expected to be explicitly enabled using option named like `SlicerMorph_BUILD_MODULE_<ModuleName>` where `<ModuleName>` corresponds to the name of the sub-directory.

* When `SlicerMorph_BUILD_DEFAULT_MODULES` is `ON`
  * If `SlicerMorph_BUILD_MODULE_<ModuleName>` is set to `OFF` (either explicitly or by virtue of existence of entries in the cache), it will be ignored and warnings will be reported.

cc: @lassoan @jadh4v

**Comment by jcfr** [comment]
Since the set of dependent extensions listed in `EXTENSION_DEPENDS` may change based on the required modules ... this may become more complex than anticipated.

**Comment by lassoan** [comment]
Probably SlicerMorph module is too big. One solution for more efficient reuse of modules would be to move out group of tightly related modules into separate repositories. The SlicerMorph would serve as a "meta-extension", which would install a list of extensions that are useful for morphology researchers. Splitting up large extensions have many other advantages, such as users can discover general-purpose modules more easily, because they show up in the extension manager; limits the impact of build error of a module; etc.

If this moving out desired modules to a separate extension is not feasible then we may not need a `SlicerMorph_BUILD_DEFAULT_MODULES` option but we could disable modules the same way as we already do it for Slicer core modules: https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/CMakeLists.txt

**Comment by lassoan** [comment]
> Since the set of dependent extensions listed in `EXTENSION_DEPENDS` may change based on the required modules ... this may become more complex than anticipated.

If I remember correctly, when we build a custom application, extension dependencies are not processed automatically, but you need to manually add all dependent extensions in the correct order.

**Comment by muratmaga** [comment]
Actually we have an issue open to this 
https://github.com/SlicerMorph/SlicerMorph/issues/195

We just didn't get around it. @jcfr would this suffice for you?

**Comment by jcfr** [comment]
> but you need to manually add all dependent extensions in the correct order.

Indeed, in the context of custom application, the value of `EXTENSION_DEPENDS` is currently irrelevant and developer is assumed to explicitly include the relevant dependencies. 

> Actually we have an issue open to this https://github.com/SlicerMorph/SlicerMorph/issues/195. [...] would this suffice for you?

Extracting history of "convenience tool" like `ImageStacks`, `Animator`, ... and pushing into dedicated repositories would be ideal as it would enable composing application more easily.

In the short term, the following could be done:

* extract history using approach described in https://github.com/Slicer/Slicer/pull/4765/commits/d9e129dcab7af6d40b0ef1208d1769977495bc3d

* include module into SlicerMorph wrapping `FetchContent_Populate` into a convenient function.

This would avoid introducing additional runtime steps and keep the current user experience the same. 

In the future, dedicated extension could be created as well ...

**Comment by SlicerMorph** [comment]
> Extracting history of "convenience tool" like `ImageStacks`, `Animator`, ... and pushing into dedicated repositories would be ideal as it would enable composing application more easily.

Those are actually core modules of SlicerMorph extension, convenience tools I mention in the referenced threads are modules from other extensions such as DCM2NIIX, Lights, Cross-sectional geometry (Sandbox), extra segmentation effects, Fiducial registration/Texture Models (IGT) so forth.

I will defer this to @smrolfe and @pieper

**Comment by pieper** [comment]
Yes, I think tools like Animator, MarkupEditor, and ImageStacks would have a more general audience, yes.  Perhaps they even belong in the core, although Animator at least could stand another round of improvements.

@jcfr which modules did you want use in your custom app?

**Comment by muratmaga** [comment]
I think this is address with https://github.com/Slicer/ExtensionsIndex/pull/1825
