### ISSUE TITLE
Better customization of the preferences for SLicerMorph

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#21]
From Andras's response on discourse:
Custom settings panel 
https://discourse.slicer.org/t/application-startup-script-open-option-is-confusing/9596/2

**Comment by SlicerMorph** [comment]
@pieper did you have a chance to think about this?

**Comment by pieper** [comment]
Yes, creating a custom settings panel should be no problem at all.  Maybe the best place to start is to define one or two key values that we'd want to set and implement the infrastructure.  From there it will be easy to add setting and modify the design as we see fit.

**Comment by muratmaga** [comment]
@pieper 
@smrolfe 
We have been adding quite a bit of stuff  .slicerrc.py file for SlicerMorph specific customization (like custom layout, segment editor keystrokes, disable compression). There are bunch of other remaining things that we haven't address yet (locations of temp and cache for download files, GPU rendering setting -Normal as oppose to adaptive). I am putting this as a reminder to get back. Here is the most current version of the customization we are asking the users to do manually:

https://public.boxcloud.com/d/1/b1!qYXRCEmmkbdDA_1ee-ZKZL7rT5hp6vFgEvJ6QcqHApbyEy5suqwyy0TosZdLaGtfk4qzJPYC2rub7G2O-WD-b2H-28Vy_nVwKhxrGrJCDRMS-l0vmurUUFBXlahJ1OlHd8ODb-1BsjaVQ_DSi2b5Xos5UVStPMmq1-ZC_0ZyHtr3mALMdyoKM6CgepAYuwg6o5lC68vxR6wWABoSMLRazk9T3HXQ7dDd9ldwmJbYLgcDmf_dwQx2S6OPVloE0v1GrJ_wiCDhBTHcOpaE1puQXieLMYGqiqJZbFeklSPE0SBcEd40OAUaOxVtWob63-E2rCjZ3zWYpgrInaUNBmRNtvoaSJCNe90gsBN6uT6AeMyVdOMULSL6Og1E-0ZBjdML7gPD4VYwik_pRSYAyISI6TnLVm5XvDslm2xX8Ut8R5q4yKOUyRyUmOCYohVu3xEA6eAZgf_cZpHOHGh0AjAfKpCr17APw4TRq7ZBplZhz5TeZH4fmSymC2KksN04v4JQYFS3xwqxre1cs4wFxbXijhhd_5uT4GUTNvf0s88KX8A9zlpdALbps78v4ie1Ublcv_mrAUR0wOpARQ7jeI91wBkMW6UU7WtIw9V8VlPz0VhajbMljnbSMPSgpj8-On_nnk4r1RheEsHW1_NYBL60tHK4TVKc6QEVqTCYxnjLFmuIKEZENZUZ0WFSV-tC1khacII6KaZRp6GWbeGrfIEuWoWeZbrYDv6YBmHm3en937hLvCTsoklEdTDmW9Vn8Wfl1-vnS-Egmlr4uxNxXNrzdF_HvcrFkLtc6MfPFS6XdWbPZOGlFzMwzo1I5A-DpxeG9L7qq4F7XOeG6WpZsHndHsOCz8f6ge9jrjuB-zoB-Zl-L4jJozZCaqf8wZRpH-Zbmtt-_5JWcAGXxREzHLDmkv3HVMI8ruBy66gRnb1_20lJnyS_eIr88P23rLXBg0wplncdRPo_GQYmJapkY-1WF1zSA_xb6ZDRZ3SyDHzQeFfzbnzuZAAEhU5iqz2E6XidfRjQidjkD9BODFXisNk99cEhFsETHRo18NfyhGZzHK7vtmx4EJ6FAa3sef1mNabIkQhy39mV70UR1B-c4WonVYvxfldT3UJXxQfk1Pq-oTBufBwmXxsYRKGaUl0ZMASvopjxVrX8ELKD6z8Eoj_VLcqRFQDHibyC5UQIVCh0d0pOc2fUgOHDPRVdnrZ_DKk7LjZjR1ltA7UXBaI7qgcZ0KEiS3kmIHkMgSa4qewkpl5xEU_10gJ88r7UQKYQOBiOMDO8spkGjf1tnt3TGkY./download

**Comment by muratmaga** [comment]
Fixed with @SlicerMorphPrefs module
