### ISSUE TITLE
Cropping RGB values with ImageStacks throws an error

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#215]
Step to reproduce: This works. 
1. Select a few RGB files in Imagestacks.
2. Set the ROI to full volume
3. Uncheck Grayscale option
RGB stacks loads fine. 

Repeat the steps with setting an ROI and see that it throws the error below,  even if you explicitly specify to create a VectorVolume as the output volume.

```
Loading failed: Select a vector volume as output volume or force grayscale output.
Traceback (most recent call last):
  File "C:/Users/murat/AppData/Local/NA-MIC/Slicer 5.0.2/NA-MIC/Extensions-30822/SlicerMorph/lib/Slicer-5.0/qt-scripted-modules/ImageStacks.py", line 395, in onLoadButton
    outputNode = self.logic.loadVolume(self.currentNode())
  File "C:/Users/murat/AppData/Local/NA-MIC/Slicer 5.0.2/NA-MIC/Extensions-30822/SlicerMorph/lib/Slicer-5.0/qt-scripted-modules/ImageStacks.py", line 697, in loadVolume
    raise ValueError("Select a vector volume as output volume or force grayscale output.")
```

@pieper @lassoan @smrolfe

**Comment by muratmaga** [comment]
> Repeat the steps with setting an ROI and see that it throws the error below, even if you explicitly specify to create a VectorVolume as the output volume.

Actually, it doesn't have anything to do with ROI. I think int he second and subsequent steps vectorvolume node is not created correctly. Because subsequent attempts fail with the same error even without an ROI (which clearly works for the very first run).

**Comment by lassoan** [comment]
Pushed a fix.

**Comment by muratmaga** [comment]
Still getting an error:


Switch to module:  "ImageStacks"
After downsampling, /home/docker/mydata/Downloads/all/DSC_1000.jpg size is 2320 x 2728

/home/docker/mydata/Downloads/all/DSC_1097.jpg size is 2232 x 2312 (3 scalar components)
Loading failed: 'tuple' object has no attribute 'shape'
Loading failed: 'tuple' object has no attribute 'shape'
Traceback (most recent call last):
  File "/home/docker/mydata/Downloads/Slicer/NA-MIC/Extensions-30822/SlicerMorph/lib/Slicer-5.0/qt-scripted-modules/ImageStacks.py", line 395, in onLoadButton
    outputNode = self.logic.loadVolume(self.currentNode())
  File "/home/docker/mydata/Downloads/Slicer/NA-MIC/Extensions-30822/SlicerMorph/lib/Slicer-5.0/qt-scripted-modules/ImageStacks.py", line 673, in loadVolume
    firstArrayFullShape.shape[2] if len(firstArrayFullShape.shape)==3 else 1,
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by lassoan** [comment]
Probably you need to remove `.shape` (it will be just `firstArrayFullShape[2]`).

**Comment by SlicerMorph** [comment]
It works now but we still need to an error catching for corner case:  Load successful an RGB imagestack, follow this by a second image selection with mismatched dimensions and choose to overwrite the original RGB volume. This generates an error.
