### ISSUE TITLE
Implemenent Boas coordinates as an option for GPA module

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#218]
As described by Bookstein 2021 (https://link.springer.com/article/10.1007/s11692-020-09530-w) and [discussed in here:](https://groups.google.com/g/geomorph-r-package/c/Qzt689gcyz0)

This should be a checkbox that says "Enable Boas Coordinates", in which if checked we should multiply the resultant procrustes coordinates with the specimens centroid size. All PCA and other downstream analysis should use these coordinates. This option has the benefit of re-introducing the size back to the analysis, but still doing the alignment without the size (which can be an issues for very different scales).

Obviously this needs to be XOR with respect to the skip scaling option (that is if skip scaling is enabled, people cannot choose boas coordinates option).

**Comment by muratmaga** [comment]
Completed via https://github.com/SlicerMorph/SlicerMorph/commit/b3359c517553e90e0b8ce10fad3673417e716bc7
