### ISSUE TITLE
Add a tab to GPA module for creating heat maps

### ISSUE THREAD

**Issue by smrolfe** [SlicerMorph/SlicerMorph#219]
Add a tab to the GPA module to create heat maps similar to those Kelly generated for her zebrafish project.

Kelly made a mockup of the interface here: [here](https://www.figma.com/file/NkRIc1xleI7KNeE3zGvCSE/Heat-maps-for-GPA-module) to help visualize what a potential new "heatmaps" tab could look like. 

The current plan is to have two dropdown selectors with corresponding sliders to choose and set the contributions of up to two PCs. This would look similar to the PC warping setup. A graph would show the current values as a point in a plot of PC X/PC Y. A checkbox would allow the sliders to be tied together so the point can only move along the X=Y line. If the heat map can be updated quickly enough, it should be linked to the sliders.

Optionally, this module may also provide access to some scalar display options that are buried in the models module, such as colormap selection and min/max displayed range.

**Comment by SlicerMorph** [comment]
I think as part of this, we should explore the option of interacting with PCA plots. THat will probably give a lot more flexibility in terms of use compared to a lot of dropdowns.

**Comment by smrolfe** [comment]
Yes, that's what I was attempting to describe. The dropdowns are just to select the PC.

**Comment by smrolfe** [comment]
![GPANewTab](https://user-images.githubusercontent.com/43060230/173153252-746eb496-4d35-4d08-acaf-69743c7fd6f4.png)

Here's the updated figure. Interaction via the chart itself would be complicated to implement. Using sliders to move the point position on the plot in real-time would be one easy way around this.

**Comment by muratmaga** [comment]
also discussed here https://github.com/SlicerMorph/SlicerMorph/issues/41
