### ISSUE TITLE
Revise ImportFromURL logic for github downloads

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#228]
When viewed in a browser, a resource GH may have URL Like this:

https://github.com/SlicerMorph/SampleData/blob/master/Gor_template_low_res.vtk

This address does not work with ImportFromURL. The real address of the resource is this:

https://raw.githubusercontent.com/SlicerMorph/SampleData/master/Gor_template_low_res.vtk

I tried a few, and this seems like a very consistent mapping:
1. replace github with raw.githubusercontent
2. drop blob/ from the input URL 

It is a specific case for GH, but will simply data downloads from GH quite a bit.
@smrolfe

**Comment by muratmaga** [comment]
@smrolfe 
This is actually a better way of doing this :) This is how 3D viewer.net does it. 
https://github.com/kovacsv/Online3DViewer/blob/fefe79f09c4df6ef7a84af7e84e091183dc9f5ba/source/engine/io/fileutils.js#L92

**Comment by smrolfe** [comment]
Resolved here: https://github.com/SlicerMorph/SlicerMorph/commit/3c7e8ceedca2900fee8a9595433f41ef12668ffc
