### ISSUE TITLE
Correct PC1

### ISSUE THREAD

**Issue by XMTian** [SlicerMorph/SlicerMorph#259]
Dear developers, 

Thank you so much for designing such a great software, I have learned a lot from it. But I ran into a problem in practice. I'm studying variation in the head shape of fish. By applying GPA and subsequent PCA analysis, I did find the phenotypic variation I was expecting, but it was PC3, which accounted for only about 10%, while PC1 was the opening and closing of the fish's mouth, which accounted for more than 60%. This is because the mouths of some fishes were extremely open during the preservation process of this batch of fishes. This was indeed a mistake in our operation at that time. I am thinking of correcting PC1 so that the fish are in a standard posture, so as to facilitate subsequent research. However, I ran into a problem with the specific operation. My idea is that I reproduce the GPA+PCA analysis on the Linux platform, and then correct PC1 by subtracting the mean value from the variables associated with PC1 in a PCA analysis. I found this script https://github.com/SlicerMorph/SlicerMorph/blob/master/GPA/GPA.py, but I don't know exactly how/script to use, although all the required information is in the analysis.log file . May I ask, (1) In your opinion, is it possible for my idea to be realized? Do you have a better suggestion? (2) If possible, can you provide a script that specifically uses GPA.py?

Many thanks and all the best,
Xiaomeng

**Comment by muratmaga** [comment]
Xiaomeng, there are couple issues here:
1. There is no a priori reason for the expected phenotypic variation to be the first PC1. 
2. GPA method requires rigidly connected structures. So if the lower and upper jaws are differentially preserved (some in occlusion, and some arent), you shouldn't analyze them together.

SlicerMorph's GPA capabilities are mostly for data vetting and visualization to explore data and discover issues like you are facing. All the rest of the analytical pipeline (including inference) we expect people to use R, or write their own python scripts in Slicer. Unfortunately, the GPA module you referenced will not be much of use. 

My suggestions is would actually be to remove those points from the analysis and proceed with separate analyses for lower and upper jaws. The analytical correction you suggest may or may not work depending on the nature of the variation (i.e, it will take care of the mean change, but if your samples are not varying just that way, it won't be much of help). Separate analyses are a more safe route.

**Comment by agporto** [comment]
@XMTian I will just add one suggestion here that might accomplish what you want. There is an R package called ShapeRotator that allows for standardizing pose in articulated structures. Sounds like you might want to use it prior to using SlicerMorph.  See : https://cran.r-project.org/web/packages/ShapeRotator/

**Comment by XMTian** [comment]
Hey @muratmaga @agporto, thanks for your comments, I will try the steps you suggested.
