### ISSUE TITLE
mean shape landmark visualized in viewer #2 should the deformed shape's

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#26]
When a 3D model and corresponding set of landmarks are selected to visualize 3D deformations, and the toggle mean shape landmarks is enabled, the mean landmarks shown in viewer #2 (deformed model) should the deformed mean shape one. Otherwise they just interfere with the visualization and make it harder. 

![image](https://user-images.githubusercontent.com/45026482/72763942-cf786e00-3b9a-11ea-9719-4007186e9b52.png)

**Comment by smrolfe** [comment]
The next version will warp the position of the mean shape landmarks in the deformable model viewer.

**Comment by smrolfe** [comment]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/43060230/74004944-2d8faa00-492c-11ea-90cb-3f15532e3d41.png">
