### ISSUE TITLE
Sample data set loading is broken

### ISSUE THREAD

**Issue by lassoan** [SlicerMorph/SlicerMorph#264]
Maybe the behavior is intentional, but the user experience is not good. I clicked on the "Gorilla Skull Reference Model" and instead of the model appearing on the screen, a file selector popup opened. I tried other SlicerMorph data sets and it had the same issue. After a while I realized that I need to select a folder and realized that the title is "Destination Folder", so I created a new folder and selected it. At this point I really expected to see the model show up, but still nothing. I clicked the data set again, hoping that it have download the file and now it will be able to load it - but still nothing. Very annoying.

The main goal of Sample Data module is to easily get sample data by a single click - no need to think about where the data is downloaded from, where is it stored, and how it will be opened. SlicerMorph breaks all these - it forces me to make decisions and requires about 10-20 clicks and some keyboard usage to get the data in Slicer.

If you want the users to download a file to their computer from a website then you can simply show a URL of a download page (that has links to your data sets).

**Comment by muratmaga** [comment]
Thanks for the feedback. Unfortunately the current behavior come as a part of compromise due to multiple factors. Most of our sample data are not meant to be load directly into Slicer, but meant to be read from the disk as part of the analysis. If we do not prompt the download folder as an option, most of our users cannot find where they are downloaded (since the RemoteIO is under a buried, OS specific temp folder.

**Comment by lassoan** [comment]
> Most of our sample data are not meant to be loaded directly into Slicer, but meant to be read from the disk as part of the analysis.

Probably this is the root cause of all the problems. Keeping files on disk instead of added to the scene breaks many features. Not just sample data but data saving/restoring (scenes are not self-contained anymore), input/output data selection in modules (you need to keep using file selectors), data display (data that is not loaded cannot be displayed), etc.

Since now custom file readers/writers can inspect files and can claim them (by return higher confidence value than generic readers/writers), you can customize how each file is loaded exactly (e.g., the same .json or .csv file can be processed very differently depending on what it contains). So, it should be no problem reading any files into the scene that you need to process or visualize.

There are data sets (AI models, atlases, etc. let's just call them "atlases") that don't need to be loaded into Slicer and would be impractical to be stored with the scene (because they are large and never change). These are very different from user data (input/output data sets that users want to load, process, visualize) and very different from sample data sets (example user data), so they need to be handled differently (e.g., they should not show up in Sample Data module). Modules that need to deal with atlases can already use the existing infrastructure (CacheManager and utility functions in SampleData module logic) to download and manage data. We could improve this by adding some metadata to the cached files, for example what module uses it, persistence flag (prevent automatic removal when the cache is full), priority (to prioritize keeping atlas files in memory), version information, checksum, etc.

**Comment by muratmaga** [comment]
We will revisit the SlicerMOrph Sample Data module sometime in summer, keepign it opeen
