### ISSUE TITLE
FastModelAlign does not work in Slicer-5.2.2 on Windows

### ISSUE THREAD

**Issue by lassoan** [SlicerMorph/SlicerMorph#266]
I've tried to use the just-announced FastModelAlign module, but I've ran into some issues and noted a couple of improvement possibilities:
- Sample data sets are incorrect, they are some brain images, probably from the module template. It would really help if you provided actual models that the module can register.
- Cannot save the computed transform. The most important thing a registration module does is that it computes a transform. It can be convenient if it can also apply or harden that transform on a node, but that's most of the time is not sufficient.
- Cannot click `Test pointcloud subsampling` or `Run rigid registration` until a new `Output registered model` is selected (keeping the default `(Create new model)` option does not make the buttons enabled)
- Clicking `Test pointcloud subsampling` has no effect. These appear in the error log:

```
parameters are  {'pointDensity': 1.0, 'normalSearchRadius': 2.0, 'FPFHNeighbors': 100, 'FPFHSearchRadius': 5.0, 'distanceThreshold': 3.0, 'maxRANSAC': 1000000, 'ICPDistanceThreshold': 1.5}
:: Loading point clouds and downsampling
Scale length are   121.82725646694595 340.21965251777857
Voxel Size is  2.2150410266717446
------------------------------------------------------------
movingMeshPoints.shape  (5660, 3)
movingMeshPointNormals.shape  (5660, 3)
fixedMeshPoints.shape  (809, 3)
fixedMeshPointNormals.shape  (809, 3)
------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/FastModelAlign.py", line 276, in onSubsampleButton
    ) = logic.runSubsample(
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/ALPACA_preview.py", line 2904, in runSubsample
    target_fpfh = self.get_fpfh_feature(
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/ALPACA_preview.py", line 2789, in get_fpfh_feature
    import itk
ModuleNotFoundError: No module named 'itk'
```

- `Run rigid registration` fails, too  - has no effect and these errors appear in the log:

```
parameters are  {'pointDensity': 1.0, 'normalSearchRadius': 2.0, 'FPFHNeighbors': 100, 'FPFHSearchRadius': 5.0, 'distanceThreshold': 3.0, 'maxRANSAC': 1000000, 'ICPDistanceThreshold': 1.5}
:: Loading point clouds and downsampling
Scale length are   121.82725646694595 340.21965251777857
Voxel Size is  2.2150410266717446
------------------------------------------------------------
movingMeshPoints.shape  (5660, 3)
movingMeshPointNormals.shape  (5660, 3)
fixedMeshPoints.shape  (809, 3)
fixedMeshPointNormals.shape  (809, 3)
------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/FastModelAlign.py", line 353, in onApplyButton
    self.sourcePoints, self.targetPoints, self.scalingTransformNode, self.ICPTransformNode = logic.ITKRegistration(self.sourceModelNode, self.targetModelNode, self.ui.skipScalingCheckBox.checked,
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/FastModelAlign.py", line 468, in ITKRegistration
    ) = logic.runSubsample(
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/ALPACA_preview.py", line 2904, in runSubsample
    target_fpfh = self.get_fpfh_feature(
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/ALPACA_preview.py", line 2789, in get_fpfh_feature
    import itk
ModuleNotFoundError: No module named 'itk'
```

- `Run affine registration` button is disabled (maybe result of failed rigid registration?)
- Add spaces to module title - `Fast Model Align`
- Rename `Skip scaling` option to a positive statement (`Enable resizing`, `Enable scaling`, `Scaling`, ...). Negative statements makes the GUI harder to read ("enable/disable skip scaling" or "select/unselect skip scaling" are a bit confusing).
- Module icon has white background (it should be transparent)

**Comment by muratmaga** [comment]
Thanks for the feeedback@lassoan. It should run on windows, but I think what happened is,  you never used the ITK-ALPACA, which automatically bring the necessary ITK python packages at the first instantiation. So if you can enable testing and then just navigate the alpaca_preview from the module finder, and wait it for to install the python libraries  then please retry.  

@smrolfe can you add that automatic module switch to avoid this issue. 

also we will post the sample datasets to your SlicerMorph sample, just didn't have time. Meanwhile you can try with these: https://seattlechildrens1.box.com/v/modelRegistrationSamples

**Comment by lassoan** [comment]
After switching to `ALPACA` module, some python packages were installed. Still, `import itk` returns with error.

**Comment by agporto** [comment]
@lassoan I think @muratmaga meant the alpaca_preview .. the main alpaca still uses open3d (instead of itk) internally. In any case, this should be handled by the module and will need to be updated.

**Comment by lassoan** [comment]
I don't see such module. Maybe it is only available in recent Slicer Preview Releases?

**Comment by agporto** [comment]
This is the module: https://github.com/SlicerMorph/SlicerMorph/blob/master/ALPACA/ALPACA_preview.py#L180C1-L220C62
It is being imported in the current module, but the entire installation procedure is currently located in the ALPACApreviewWidget.setup(), which does not get called

**Comment by muratmaga** [comment]
> I don't see such module. Maybe it is only available in recent Slicer Preview Releases?

You have enable testing option in the module finder and make sure developer mode is on. 
![image](https://github.com/SlicerMorph/SlicerMorph/assets/21285140/47e78880-50c5-4ba5-9ab2-fc4d8320ed62)

There is still one bug in the ITK implementation that I am hoping @jcfr or Matt McCormick can fix before we deprecate the open3d based ALPACA, and make the ALPACA_preview the default one.

**Comment by smrolfe** [comment]
I have created a[ pull request](https://github.com/SlicerMorph/SlicerMorph/pull/267) with a quick fix that we can test and run asap. As @muratmaga suggested, it checks libraries that trigger the Alpaca_preview installation steps and toggles between the modules if not found.
