### ISSUE TITLE
Display of warped and original image in deformable viewer

### ISSUE THREAD

**Issue by smrolfe** [SlicerMorph/SlicerMorph#28]
This can occur after making several changes to viewing options, PC warping, and mean shape display.

**Comment by SlicerMorph** [comment]
same as #26

**Comment by smrolfe** [comment]
Not replicated.

**Comment by smrolfe** [comment]
This was a little different than #26, the warped model and the original were occasionally displaying in the same window. It's likely to have been resolved by the other updates.

**Comment by smrolfe** [comment]
These bugs should all be resolved by the last update to the GPA module: 6a027d11f10119031d06a10278ca679037480fc6
