### ISSUE TITLE
Move the deformed mean shape points in the viewer #2 even without a 3D model

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#29]
@smrolfe 
This will facilitate visualization of PC scores without needing a model. This would be a nice dynamic visualization supplement to the lollipop plots, which gives a static view of PC vectors.

**Comment by smrolfe** [comment]
![image](https://user-images.githubusercontent.com/43060230/74009888-0c818600-4939-11ea-8c0d-77f6f87bf419.png)
![image](https://user-images.githubusercontent.com/43060230/74009907-14412a80-4939-11ea-9157-22bb4e7bf654.png)
