### ISSUE TITLE
Add a radio button to turn on/off visibility of mean landmark labels

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#31]
As requested from Shan Shan

**Comment by smrolfe** [comment]
commit 8e5e6d17a873104d23c132c2e3642de6ffe86992

**Comment by smrolfe** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/43060230/74009648-85cca900-4938-11ea-9c4c-59c1a4f47149.png">
