### ISSUE TITLE
Can't run GPA with loaded landmarks in json format 

### ISSUE THREAD

**Issue by aConar** [SlicerMorph/SlicerMorph#314]
Hi everyone,
While working with old JSON files containing landmark data, I noticed that I'm unable to run GPA when loaded into Slicermorph. However, when I save them in the fcsv format, they load without any issues, and GPA runs smoothly.
To test this behavior, I experimented with the sample data. I downloaded the mouse skull landmark data in fcsv format, saved them as  JSON files (mrk.json), and then loaded back into the Slicermorph module. However, upon clicking the 'Execute GPA + PCA' button, nothing happens.
Any help will be appreciated!
Regards,

Ale

**Comment by muratmaga** [comment]
I cannot replicate this behavior with mouse sample data exported as JSONs from Slicer. Everything works as expected. 

How did you export the JSONs from Slicer? Also check the log file, there might be clues why it is failing. Also what's the version/OS of your Slicer? 

<img width="1643" alt="image" src="https://github.com/SlicerMorph/SlicerMorph/assets/21285140/803fb0c7-6b74-4a5d-8eb0-74056f3dabe8">

**Comment by muratmaga** [comment]
closing since we can't replicate and haven't heard back from the user.
