### ISSUE TITLE
QuickAlign is not working with models

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#319]
Currently the code is hard wired to link volumes, but the whole point was to be able to render two object in sync with similar starting position, we probably need to update this to work with markups and models at the minimum and it to the tools.

**Comment by muratmaga** [comment]
This is probably doen with in conjuction with MarkupLink. it suffers from a centering problem.

**Comment by smrolfe** [comment]
Working branch here with translation fix: https://github.com/SlicerMorph/SlicerMorph/blob/QuickAlignUpdate/QuickAlign/QuickAlign.py

The Slicer application crashed once while testing this but there was no error generated and I haven't replicated.

**Comment by muratmaga** [comment]
Did you also add the model data type? This needs to work with models as well.

**Comment by smrolfe** [comment]
The newest branch is up with the translation fix and includes models. I also made updates to support transforming multiple nodes per viewer when we're ready to add this to the interface.

**Comment by smrolfe** [comment]
Merged here: [Merge pull request](https://github.com/SlicerMorph/SlicerMorph/commit/11ff4a7199621032d5cf0f199560d163b0b43221)
