### ISSUE TITLE
unable to read in markups json files for GPA on Mac

### ISSUE THREAD

**Issue by drScanley** [SlicerMorph/SlicerMorph#327]
**Describe the bug**
I am running 3Dslicer version 5.6.2 and slicermorph from May 16th on a mac. I am unable to select markup json files from the browser when trying to run PCA on the GPA modlue. They are greyed out and unselectable. Thanks!

**Comment by muratmaga** [comment]
@drScanley I can't replicate this on my mac with the latest SlicerMorph. Couple things to check:

**Comment by drScanley** [comment]
Thanks @muratmaga. I can select fcsv files from the folder but not Json, and moving the files has no effect.  The slicermorph is the most recent version. The dataset can be downloaded from [here](https://www.dropbox.com/scl/fo/f4g3c4koocvv64hm5tjvo/AFj52RZJIq5Awo6g37awwDc?rlkey=k3a2c957onw2cfmgct72gp89r&dl=0). Thanks!

**Comment by muratmaga** [comment]
Thanks for sharing. Now I can replicate. @smrolfe looks like our pattern matching is forcing the "mrk.json" as file selection criteria. Hence making these JSON files unselectable, even though they are valid. Can you fix that please?

@drScanley as a work around, please rename the file from .json to .mrk.json and things seems to work.

**Comment by smrolfe** [comment]
Both should be allowed and I am only seeing this issue on the Mac OS, Windows is fine. I will look into it further.

**Comment by muratmaga** [comment]
@smrolfe any updates on this?

**Comment by muratmaga** [comment]
This also happens in Mac. @smrolfe can you please address this?

**Comment by smrolfe** [comment]
Submitted the bug fix here: [Update json selection syntax](https://github.com/SlicerMorph/SlicerMorph/commit/e34216eb839224eb0d5fe3771606ea3227ac91c0)
