### ISSUE TITLE
HiResScreenCapture improvements

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#342]
HiResScreenCapture module (available only for preview builds), works but UI is very ugly (see below), and works differently from every other Slicer module. It also restricts saving only as PNG (not sure why). 

1. Saving the output directly to the scene, and then let the user save whichever format they want from the ExportAs File interface.
2. alternatively, revise the UI to choose the file path and allow other formats. 
3. It is saving the topbar (blue bar) from the 3D viewer. This is unnecessary.
4. There is no communication of task being complete beyond the file is generated. 

<img width="609" alt="image" src="https://github.com/user-attachments/assets/bbd59ff6-98f8-4d96-935c-51f0821317f6">

**Comment by oothomas** [comment]
Hi,

I believe adding save type options is possible, I’ll also add an image saved dialog box that displays the file path so the user knows it’s done.


Sent from my iPhone

On Sep 3, 2024, at 4:01 PM, muratmaga ***@***.***> wrote:

﻿

HiResScreenCapture module (available only for preview builds), works but UI is very ugly, and works differently from every other Slicer module. It also restricts saving only as PNG (not sure why).

  1.  Saving the output directly to the scene, and then let the user save whichever format they want from the ExportAs File interface.
  2.  alternatively, revise the UI to choose the file path and allow other formats.
  3.  It is saving the topbar (blue bar) from the 3D viewer. This is unnecessary.
  4.  There is no communication of task being complete beyond the file is generated.

**Comment by smrolfe** [comment]
Updates to output file types, intial directory, and invalid path error checking here: 78ce89e608a9ee04629ade9d1daf42269613b385

**Comment by smrolfe** [comment]
Added TIFF extension to output types: 8484800167b0f463acb97c63388231bc20568f10
