### ISSUE TITLE
Do not load the reference model if the number of LMs does not match and display a meaningful error message

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#356]
When the user choose a model for 3D interactive visualization, and the chosen reference LM set does not contain correct number of LMs, the model is still loaded into the scene. A VTK error message is displayed in the python console (if open) that says `[VTK] Update: Source and Target Landmarks contain a different number of points`

This behavior confuses the user, since if they do not see the error message (often the python console is closed). 

The correct behavior should be:

1. First check the landmark file to make sure there are correct number of LMs, and if not do not load the model into the scene.
2. Display a meaningful error to the user "selected model does not contain correct number of landmarks. X LMs are required, Y were  found"

**Comment by smrolfe** [comment]
Addressed in 4e7ee4db1f37da784d8f082713f3664e888fa7cd

**Comment by muratmaga** [comment]
verified working
