### ISSUE TITLE
Expand the Functionality of MergeMarkups with other markup types. 

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#357]
Currently MergeMarkups only merges either multiple curves, or fixed points with semiLM points (created by SlicerMorph tools). As seen on forum, this is restrictive for some people. https://discourse.slicer.org/t/merging-landmarks-and-semi-landmarks-with-slicermorph/39977

So, expand the MergeMarkup tab to allow other types of Markups to be listed. Onus will be on the user to choose the correct markup type for each set. Also allow more then two pairs to be merged.

**Comment by Ruiqi-CUB** [comment]
Thanks a lot for completing this! How do I use the new features? Just update SlicerMorph in Slicer?

**Comment by muratmaga** [comment]
It is done yet. We have discovered a few pesky bugs that we are sorting out. We will announce when it is fully done.
