### ISSUE TITLE
Default the donwload directory for the MorphoSourceImport to the default scenes path in Slicer. 

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#358]
In Slicer, the default scene location is set as a variable (Application Settings-> General)

I would like the MorphoSourceImport to default to that settings as opposed to be blank.

**Comment by muratmaga** [comment]
I think it is called:
slicer.mrmlScene.GetRootDirectory()

**Comment by smrolfe** [comment]
Addressed in b6f6ade17ae61cc28ff09022e4256c368c96e6e7

**Comment by muratmaga** [comment]
verified working
