### ISSUE TITLE
SkyscanReconImport Batch Mode log file order

### ISSUE THREAD

**Issue by raroston** [SlicerMorph/SlicerMorph#359]
**Describe the bug**
SkyscanReconImport Batch Mode shows log files out of order, making it difficult to use.

**To Reproduce**
1. Go to SkyscanReconImport and select batch mode
2. Select a directory with multiple scans
3. Push Find Log files button

**Expected behavior**
Log files should be shown in a logical order (preferably alphabetical)

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
It might be helpful to give the user multiple options of how to sort them (e.g., alphabetical, most recent, A to Z, Z to A)

**Comment by muratmaga** [comment]
what is the situation of this @oothomas.

**Comment by oothomas** [comment]
#360 complete with tutorial update.
