### ISSUE TITLE
Register GPA layout as an option in layout manager

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#39]
After choosing one of the predetermined layouts (e.g., chart, or Red slice), we cannot revert our custom layout without clicking a particular button (e.g., plot gpa). This is not trivial to new users. Either have a button in GPA, or register the custom layout with the layout manager (preferred choice).

**Comment by smrolfe** [comment]
I included this for now in the .slicerrc file. We might want to add it as a module and use the SM icon later.

**Comment by muratmaga** [comment]
Keeping it open for eventual incorporation into SlicerMorph Preferences
@pieper

**Comment by SlicerMorph** [comment]
@pieper @smrolfe please make this layout as part of slicerMorph (not just .slicerrc.py).

**Comment by pieper** [comment]
Sounds good - do you have this one @smrolfe ?

**Comment by SlicerMorph** [comment]
@smrolfe is finishing a grant application. And I think she already implemented it in this .slicerrc.py (https://seattlechildrens1.app.box.com/v/SliceMorphDownloads). Would it be possible for you to incorporate it in the right spot?

**Comment by pieper** [comment]
@smrolfe we looked at this today and it seems you already did it 👍   If it's done close this when you have a moment.  Good luck with the grant writing!

**Comment by smrolfe** [comment]
Hi Steve,
Sorry for being out of the loop, I've been out of town for the last few
days and am just getting caught up. I did implement this and will close the
issue on GitHub.
Best,
Sara
