### ISSUE TITLE
ImageStacks does not calculate the correct origin (or offset) when a partial sequence is imported. 

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#74]
This causes alignment issues if two versions (e.g., partial sequence and full sequence is loaded). 

I am not sure what how to approach this. Somehow we have to know the geometry of the full volume, but I can't think of a way to this consistently. But a way to keep these lined up correctly would be important. Especially if and when we implement the ROI based partial volume import too...

**Comment by pieper** [comment]
Certainly we cannot do this automatically, but we could give people an option to enter it manually.

**Comment by muratmaga** [comment]
OK. Let's just keep this open to discuss. 

I think it might be possible to parse the whole sequence, but then do the selection in the table. That way we would at least know where we are in the Z-stack. This would require changing the load behavior such that they need to point a folder (as oppose to select the list of files they want to load).

**Comment by pieper** [comment]
There would be a tradeoff because currently you can select a subset of files from a directory.  It seems not-uncommon to have multiple stacks in a folder with custom naming conventions.  Forcing people to put their stacks in a folder may or may not be convenient.  Anyway I'm open to doing what's most productive for the users.

**Comment by SlicerMorph** [comment]
Linking this to #122. Perhaps in parser version if less than the fullset is selected, we can calculate and write the necessary offset.

**Comment by SlicerMorph** [comment]
closed per #139
