### ISSUE TITLE
DICOM loading of any CT crashes due to Dcm2niix

### ISSUE THREAD

**Issue by cpinter** [SlicerMorph/SlicerMorph#75]
If the Dcm2niix plugin is active, then Slicer crashes when trying to load apparently any volume. See this video here:
https://1drv.ms/u/s!Ao_a-dPPX98ZhLskvBgBvirQjDDI3A?e=fOwOZP

For the record, the dataset used here is the TinyPatient dataset from the SlicerRT sample data store (please note that I only selected the CT):
https://github.com/SlicerRt/SlicerRtData/tree/master/plastimatch_tiny-rt-study

**Comment by muratmaga** [comment]
@cpinter thanks for reporting this. This is not a big deal for us, as we encourage our users to directly use dcm2niix (not through DICOMBrowser), they found it to be too confusing, and in 99% of the time there is nothing in the DICOM headers and they want is the image data.

**Comment by cpinter** [comment]
I understand, but it is very unexpected that someone installs an extension and loading the most basic DICOM data results in a crash. Even I spent some time before I realized the SlicerMorph extension was the reason.

If they don't use the loader through the DICOM browser, then I suggest simply disabling that feature so that there is no crash at such a basic operation due to this module.

**Comment by pieper** [comment]
Do we know why it crashes?  Is there an issue report?

**Comment by cpinter** [comment]
Just what I described above. It should be easy to reproduce. I don't really have time to dig into it more, but thought it would be useful to report it.

**Comment by muratmaga** [comment]
@pieper here is the log, though I am not sure if there is anything useful in it:

**Comment by muratmaga** [comment]
By the way, dcm2niix itself works fine with the sample data. It is only when DICOMBrowser is used. I guess as @cpinter suggested disabling DICOMBrowser is the easiest solution.

**Comment by muratmaga** [comment]
Closing this, as this is not specific to SlicerMorph and happens at any instance when DCM2NIIX is installed.

**Comment by pieper** [comment]
I'd suggest turning it off in SlicerMorph until we figure it out.  But for now the workaround is to open the Advanced mode in the dicom module and then open the left panel and uncheck the dcm2niix plugin.

**Comment by muratmaga** [comment]
We can't disable the DCM2NIIX, as it is our preferred way of importing DICOM images. But, if there is a way to disable (1) either the DICOMBrowser (2) or DCM2NIIX plugin for it, we can try to work that into .slicerrc.py (or wherever it is appropriate).

**Comment by pieper** [comment]
[This](https://github.com/commontk/AppLauncher/pull/117) fixes the underlying issue and is better for than a workaround.  It should be in the nightly in a day or so.
