### ISSUE TITLE
MarkupsEditor is not selecting after 

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#79]
Stopped functioning corectly after https://github.com/SlicerMorph/SlicerMorph/pull/78

It unselect everything.

**Comment by pieper** [comment]
Hmm, it works for me - are there any messages in the console?

**Comment by muratmaga** [comment]
No, nothing in python console. Do you have time for screen share?

**Comment by pieper** [comment]
yes, lets' do that - send a zoom link?

**Comment by muratmaga** [comment]
fixed with #80
