### ISSUE TITLE
potential for Data Loss in ImageStacks during back to back to usage

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#88]
When people are using ImageStacks to convert multiple stacks to volume back to back, it is easy to overwrite previously imported volume when they are not careful.

1. Import the sample_CT_stack from SlicerMorph Sample data
2. Keep the volume node none, which create a new one from the file name
3 Import the image stack
4. Clear the files from previous stack and get ready to import the next stack
5. Note that Volume Node points to the volume generated in the previous import operation, and easy to overwrite.

Solution: 
1. Not give user the flexibility to create a volume, and always import data into a new volume node using filenames. 
2. Set the volume node to back to none, right after the import is completed. 

My preference would be the second.

**Comment by pieper** [comment]
I did something a little different that I think is a little easier, but if you don't like it we can go to your option 2.

What I did is reset the node when you clear the files.  This way you can iterate on the input parameters easily without getting a bunch of nodes you need to manually delete later.  Let me know what you think.
